name: CI/CD Pipeline
on: [workflow_dispatch ,push]
jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      pipelineType: CI
      businessGroup: myBusinessGroup
  DEV: 
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      
      - run: echo "${{ secrets.Anypoint_User_Name }}"



