name: CI/CD Pipeline
on: [workflow_dispatch ,push]

jobs:
#   build:
#     uses: ./.github/workflows/build-template.yml
#     with:
#       pipelineType: CI
#       businessGroup: myBusinessGroup
  DEV:
    runs-on: ubuntu-latest
#     environment: DEV
    steps:
      - run: echo "${{ secrets.Anypoint_User_Name }}"
      - run: var="${{ secrets.Anypoint_User_Name }}" |  openssl enc -aes-256-cbc  -a -salt -k "mykey" -pbkdf2
      - run : echo $var
      - run: echo "${{ secrets.Anypoint_User_Name }}" | openssl enc -aes-256-cbc  -a -salt -k "mykey" -pbkdf2

      
      - run: echo "Mahmoud" | openssl enc -aes-256-cbc  -a -salt -k "mykey" -pbkdf2

      - run: echo "mahmoud" | openssl enc -aes-256-cbc  -a -salt -k "mykey" -pbkdf2

      - run: echo "Mahmoud" | openssl enc -aes-256-cbc  -a -salt -k "mykey" -pbkdf2


      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: s4u/maven-settings-action@v2.8.0

#       - run: mvn verify 
      - run: echo "${{ secrets.Anypoint_User_Name }}"
      - run: echo "${{ secrets.Anypoint_User_Name }}" | openssl enc -aes-256-cbc -d -a -salt -pass pass:mykey



      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "some-repository", "url": "http://some.repository.url" }]'
          plugin_repositories: '[{ "id": "some-plugin-repository", "url": "http://some.plugin.repository.url" }]'
          servers: '[{ "id": "some-server", "username": "${{ secrets.Anypoint_User_Name }} nn", "password": "some.password" }]'
          mirrors: '[{ "id": "some-mirror", "url": "http://some.mirror.url" }]'
          profiles: '[{ "id": "some-profile", "activation": { "activeByDefault": true }, "properties": { "some.property": "some.value" }, "repositories": [{ "id": "some-repo", "url": "http://some.repo.url" }] }]'

#           repositories: '[{ "id": "some-repository", "url": "http://some.repository.url" }]'
#           plugin_repositories: '[{ "id": "some-plugin-repository", "url": "http://some.plugin.repository.url" }]'
#           servers: '[{ "id": "some-server", "username": "${{ secrets.Anypoint_User_Name }}", "password": "some.password" }]'
      - name: see 
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          output_file: foo/custom.xml
      - name: display settings
        run : cat foo/custom.xml

  jon:
    runs-on: ubuntu-latest
    steps:

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "some-repository", "url": "http://some.repository.url" }]'
          plugin_repositories: '[{ "id": "some-plugin-repository", "url": "http://some.plugin.repository.url" }]'
          servers: '[{ "id": "some-server", "username": "${{ secrets.Anypoint_User_Name }}", "password": "some.password" }]'
      - name: display settings
        run : cat foo/custom.xml
      


