name: CI/CD Pipeline
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      pipelineType: CI
      businessGroup: myBusinessGroup
  DEV: 
    uses: ./.github/workflows/build-template.yml
    with:
      pipelineType: CI
      businessGroup: myBusinessGroup


